module StoneChecksums
  VERSION: String

  class Error < ::GemChecksums::Error
  end

  module Version
    VERSION: String
  end

  def self.install_tasks: () -> void
  def self.generate: (?git_dry_run: bool) -> void
end
