#!/usr/bin/env ruby
# frozen_string_literal: true

script_basename = File.basename(__FILE__)

require "bundler/setup"
require "gem_checksums/version"

if ARGV.any? { |arg| arg == "-v" || arg == "--version" }
  puts GemChecksums::Version::VERSION
  exit(0)
end

require "gem_checksums"

puts "== #{script_basename} v#{GemChecksums::Version::VERSION} ==" if ARGV.delete("--verbose")

GemChecksums.generate
