#!/usr/bin/env ruby

script_basename = File.basename(__FILE__)
require_relative "../lib/gem_checksums/version"
if ARGV.any? { |arg| arg == "-v" || arg == "--version" }
  puts GemChecksums::Version::VERSION
  exit(0)
end

require "bundler/setup"

require "gem_checksums"

puts "== #{script_basename} v#{GemChecksums::Version::VERSION} =="

GemChecksums.generate
